package com.matchome.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConvertedEnum;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;

import java.io.Serializable;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@DynamoDBTable(tableName = "Home")
public class Home implements Serializable {

    @Id
    @DynamoDBHashKey(attributeName="id")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute(attributeName="email")
    private String email;

    @DynamoDBAttribute(attributeName="zipCode")
    private Integer zipCode;

    @DynamoDBTypeConvertedEnum
    @DynamoDBAttribute(attributeName="homeStatus")
    private HomeStatus homeStatus;

    @DynamoDBAttribute(attributeName="neighborhood")
    private String neighborhood;

    @DynamoDBAttribute(attributeName="bedrooms")
    private Integer bedrooms;

    @DynamoDBAttribute(attributeName="bathrooms")
    private Double bathrooms;

}